version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=meubanco
    networks:
      - my-net
  
  db-adm:
    image: adminer
    networks:
      - my-net

  app-01: 
    image: webdevops/php-apache:7.2
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./php/:/app
    networks:
      - my-net

  app-02: 
    image: micaelortega/scriptpy
    volumes:
      - ./python/script.py:/usr/app/script.py
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - my-net

  proxy:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-net

volumes:
  my-db:
  app:
  proxy:

networks:
  my-net:
    driver: bridge